# Generated by Django 4.1.4 on 2022-12-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_start',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
